apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app # This MUST match the selector below
    spec:
      containers:
      - name: spring-boot-app
        image: koyaharikrishna/spring-boot-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot-app # This is the "glue" that finds your Pod
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001